### ISSUE TITLE
This is sad. 

### ISSUE THREAD

**Issue by PrivateGER** [CoralineAda/postmeritocracy#24]
This project proves that you think only white straight men are capable of anything.

Be the change you want to see in the world. Simple words to live by, just do something positive instead of making it worse for everyone but you.
Be the good person and others will follow.

**Comment by Leo32onGIT** [comment]
The author does not seem to realize that the definition of merit in this space is competence.
If you are good at what you do, your code is logical, critical, well-conceptualized - then you have demonstrable and valuable merit.

This 'merit', this 'competence' can come from anybody; of any background; of any ethnicity.

This manifesto is prejudicial, political.
It's as-if [this is the authors organic operating-system](https://github.com/CoralineAda/me-too-but-not-you) repo.

**Comment by lsmith77** [comment]
https://www.theguardian.com/technology/2016/feb/12/women-considered-better-coders-hide-gender-github

**Comment by sawyermade** [comment]
> https://www.theguardian.com/technology/2016/feb/12/women-considered-better-coders-hide-gender-github

Oh please, that is hogwash. Github doesn't even have a section in the user profile dedicated to gender. Also, it was from The Guardian, an extremely biased organization. Also, did you read the paper, it states that women's pulls were actually accepted more than men! They state that, "However, for contributors who are outsiders to a project and their gender is identifiable, men’s acceptance rates are higher" but somehow came to the conclusion it was bias lol. I'm not sure how you can honestly state that conclusion with a straight face. Just because a pull request was denied that was made from someone who happens to be a woman and an outsider for the project, does not equate to bias. There is no clear reasoning behind you can scientifically evaluate from the data the in the paper and I find it dubious at best that they came to this "women bias" conclusion. Read the paper https://peerj.com/articles/cs-111/, women have a 4% increase of accepted pulls over men and also make more deltas than men on avg as well. They were expecting bias, didnt find it and on the contrary found the opposite, but stated they still did find bias anyways on one statistically insignificant niche category and then The Guardian purposefuly altered what the paper said lmfao. The Guardian states that pull requests are higher when the gender is not identifiable and that is not what the paper stated. It said when they were outsiders of the project AND gender was identifiable but I still dont understand how they came to conclusion bias was the catalyst for the statistical deviation from men on that one niche metric. What a joke.
