### ISSUE TITLE
Absolutely unreasonable

### ISSUE THREAD

**Issue by TwinProduction** [CoralineAda/postmeritocracy#34]
Before all of this, I'd like to point out that I agree with _some_ of the values you promote. 
I agree that all should have an equal starting ground and should be respected regardless of their characteristics.

However, I disagree with the fact that you think meritocracy is bad.
I am a passionate developer, and I pour my soul and heart into my code.
You don't have to share my passion, but your ideology is telling me that I am inherently wrong and should thus be reprimanded for being passionate. 

> Meritocracy is a founding principle of the open source movement, and the ideal of meritocracy is perpetuated throughout our field in the way people are recruited, hired, retained, promoted, and valued.

Yes, this is to ensure that more skilled individuals are given more crucial roles to play.
Would you trust a first year med student to perform an open-heart surgery on you, or would you prefer an experienced surgeon?

> But meritocracy has consistently shown itself to mainly benefit those with privilege, to the exclusion of underrepresented people in technology. The idea of merit is in fact never clearly defined; rather, it seems to be a form of recognition, an acknowledgement that “this person is valuable insofar as they are like me.”

I hope I'm misunderstanding, but it sounds like you're blaming the majority for the fact that they are a majority while the minority is a minority. Those are not attacks - they are facts.
Furthermore, I have never seen any project where a group of people is automatically favored upon joining for being part of X group.

The idea of merit in the world of open source isn't clearly defined, because it should be obvious. 
Make good contributions. If you make good contributions and help a project move forward, then you become a valuable part of said project. 

> It is time that we as an industry abandon the notion that merit is something that can be measured, can be pursued on equal terms by every individual, and can ever be distributed fairly.

So you want communism? 

> What does a post-meritocracy world look like? 

From what I read so far, it would look like shit.

---------

# The values

> We do not believe that our value as human beings is intrinsically tied to our value as knowledge workers. Our professions do not define us; we are more than the work we do.

Speak for yourself. I devote my life and my soul to programming. 
If you don't, it's your choice and nobody can take that away from you, but **don't force your beliefs/ideology/values onto others**.

> We believe that interpersonal skills are at least as important as technical skills.

This is a dangerous statement. Are you saying that people with speech disorders and people with personality disorders should be reprimanded? 

Practice what you preach.

---------

I'll continue if I have more time later, I have things to do.

**Comment by measlytwerp** [comment]
If you disagree with this project then the appropriate response is to ignore it, maybe write a blog post about it, but not waste everyone's time by spamming the issue tracker.

**Comment by TwinProduction** [comment]
> If you disagree with this project then the appropriate response is to ignore it, maybe write a blog post about it, but not waste everyone's time by spamming the issue tracker.

This project is mostly political, how do you expect others to not voice their opinion?

**Comment by measlytwerp** [comment]
> This is open source, nobody is required to contribute.

I didn't say that people are required to contribute, but that meritocracy requires that everyone who wants to contribute is able to contribute.

> You want to skip the process of having to go through code review and you want your code to be accepted right away?

No. Maybe you should read website again, it's a fairly clear rejection of meritocracy and an affirmation of what our values are. It in no way says that bad code needs to be accepted because of the individual, instead it says treat everyone with some dignity.

We are humans building software for humans.

**Comment by michael-brade** [comment]
> > This is open source, nobody is required to contribute.
> 
> I didn't say that people are required to contribute, but that meritocracy requires that everyone who wants to contribute is able to contribute.

So what's the problem here? Are you saying that meritocracy doesn't allow everyone capable to contribute? And if so, do you have any examples of people who are able to contribute, *and* who want to contribute, *but* are prevented from doing so by meritocracy? Even better, do you have a significantly large amount of them relative to the people who want to contribute, can contribute, and are actually already contributing? 

> > You want to skip the process of having to go through code review and you want your code to be accepted right away?
> 
> No. Maybe you should read website again, it's a fairly clear rejection of meritocracy and an affirmation of what our values are.

yes, and that is what many have a problem with. The reason for this clear rejection is not clear, and I don't agree with this superficial explanation on wikipedia.

> It in no way says that bad code needs to be accepted because of the individual, instead it says treat everyone with some dignity.

It doesn't say that, yes, and neither does it say that you are free to have any opinion, political view, etc. Why? Because this is not what is desired? If it is desired, then why not add it? After all, we are all about code, not politics; so has politics suddenly become more important than code?

> We are humans building software for humans.

Agreed.

**Comment by fork32** [comment]
Let free software die.

the "post meritocracy" means less code more gender.

less quality more diversity.

I have no aguments in favor of free software anymore. Quality, security, will end soon. Projects are being taintes one by one by SJW.

I'll not fight against anything, I can have choices and I choose to quit free software and go closed source.

**Comment by sawyermade** [comment]
Yeah, this whole thing is more or less just a silly joke. Merit is the best metric for the job, it is based solely on accomplishments/experience, performance, and quality (in our case, the quality of our code). Merit is color blind and doesn't give a shit about what color your skin is, what country you were born in, what sex or gender you are, or sexual orientation (you cant deduce any of this from reading code lol) and that is what so great about it. Removing meritocracy is in fact, ironically, extremely racist. Instead of choosing based on who is best for the job, you have a quota you try to fill instead, hence accepting and rejecting people based on demographics of race, sex/gender, etc. I think all these SJWs have gone full retard and this manifesto is obvious proof of that. Ridding the world of merit is an idea that you shouldn't have to work to earn what you desire or be responsible for your choices. You should just be given things bc... equality? Please, don't insult our intelligence. We don't,  shouldn't, and hopefully never have equality of outcome but we should strive for equality in opportunity, which can always be improved. Focus on equality of opportunity bc equality of outcome just doesn't make sense at all since it punishes the hardworking and rewards the lazy.

**Comment by anarchistmae** [comment]
> Please, don't insult our intelligence.

Why would I try when you do it so well yourself.

**Comment by sawyermade** [comment]
> > Please, don't insult our intelligence.
> 
> Why would I try when you do it so well yourself.

How does one insult their own intelligence? You make less and less sense the more you speak, so try to do less of it, please.

**Comment by anarchistmae** [comment]
Are you having a crisis or something? What made you come hear an entire year after the last comment and think your input was needed by anyone? Just exactly how enormous is your ego?

**Comment by sawyermade** [comment]
By all your comment ratings, it seems like you're the one whos input isnt needed. Honestly, you are the only one personally attacking people on here instead of arguing a valid point. Typical SJW shit though, when you don't have a solid point or the intelligence to debate it, personally attack them with a smug attitude and reflect your own shortcomings onto them. Ad hominem much?

**Comment by anarchistmae** [comment]
Not my fault you cannot spot the childish flaws in your own argument.

**Comment by sawyermade** [comment]
> Not my fault you cannot spot the childish flaws in your own argument.

And obviously neither can you.

**Comment by anarchistmae** [comment]
No but you.

**Comment by anarchistmae** [comment]
You're really mad about this huh.
